package com.epam.task3.controller.commands;

public enum CommandName {

     ADD_NEWS,
     GET_NEWS_FREE_CRIT,
     GET_CONCRETE_NEWS,
     GET_NEWS_BY_CATEGORY,
     GET_NEWS_BY_TITLE,
     GET_NEWS_BY_CREATOR,
     GET_NEWS_BY_TITLE_AND_CATEGORY,
     GET_NEWS_BY_CREATOR_AND_CATEGORY,
     GET_NEWS_BY_TITLE_AND_CREATOR,
     WRONG_COMMAND,
     WRONG_REQUEST,
     EXIT

}
